server:
  port: ${port:0}

spring:
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:mysql://localhost:3306/db_d001b002_entity_mysql?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Mul7417064.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  renewalPercentThreshold: 0.85
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

