server:
  port: ${APP_PORT}

spring:
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:postgresql://localhost:5432/db_d001b001md_postg?currentSchema=sc_md&ssl=false
    username: admin
    password: Casa7417064.
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true




eureka:
  renewalPercentThreshold: 0.85
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


service:
  security:
    secure-key-username: sgiSecureUsername
    secure-key-password: sgiSecurePassword!
    secure-key-username-2: sgiSecureUsername2
    secure-key-password-2: sgiSecurePassword2!