spring:
  application:
    name: security-gateway-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_d001b002seg_mysql?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: admin_gateway
    password: Casa7417064.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: false